hydra-genetics/biomarker

- .github/workflows/integration.yaml
> fix: integration test conda

- workflow/rules/tmb.smk
- workflow/scripts/tmb.py
- workflow/scripts/tmb_test.py
> feat: run TMB without background runs calcualtions

- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
- .github/workflows/pycodestyle.yaml
- .github/workflows/pytest.yaml
- .github/workflows/snakemake-dry-run.yaml
> refactor: remove conda setup from dry-run

- README.md
> docs: update compatibility versions

- .github/workflows/integration.yaml
- README.md
- workflow/envs/hrd.yaml
- workflow/envs/msisensor_pro.yaml
- workflow/envs/optitype.yaml
- workflow/envs/scarhrd.yaml
- workflow/envs/tmb.yaml
- workflow/rules/msisensor_pro.smk
- workflow/rules/optitype.smk
- workflow/rules/scarhrd.smk
- workflow/rules/tmb.smk
we will drop support for conda, since it constantly breaking even though code hasn't been updated.
> feat: remove conda support and testing

- COMPATIBILITY.md
> docs: update compatibility

- workflow/scripts/tmb.py
> fix: added newline between variants

- COMPATIBILITY.md
- workflow/scripts/tmb.py
> chore: dev to master

- .readthedocs.yaml
> fix: add missing file used by readthedocs

- README.md
> docs: update rtd links

- workflow/schemas/config.schema.yaml
> docs: rtd update

- requirements.txt
> feat: Update snakemake version in requirements.txt

- workflow/rules/optitype.smk
> fix: rm prefix parameter in optitype

- requirements.txt
> chore: Update requirements.txt

- .github/workflows/integration.yaml
> chore: Update integration.yaml

- .tests/compatibility/config.yaml
> fix: Update config.yaml

- .github/workflows/pycodestyle.yaml
- .github/workflows/pytest.yaml
- .github/workflows/snakefmt.yaml
- .github/workflows/snakemake-dry-run.yaml
> test: upgrade action version to v3

- .github/workflows/integration.yaml
> test: fix ubuntu version

- .github/workflows/integration.yaml
> test: rm conda path

- .github/workflows/integration.yaml
> test: set ubuntu latest with apptainer-suid

- workflow/rules/tmb.smk
- workflow/schemas/config.schema.yaml
- workflow/scripts/tmb.py
- workflow/scripts/tmb_test.py
> feat: improved ctDNA tmb
